### ISSUE TITLE
Ventura support

### ISSUE THREAD

**Issue by seidnerj** [arusson/macos-tls-keylogger#1]
Is the offset the same in ventura? If not, how can I calculate it? I was going to disassemble the dylib but /usr/lib/libboringssl.dylib doesn’t exist on my system.
 
Thanks in advance!

**Comment by arusson** [comment]
Yes, since libraries have been merged as one big file since Big Sur.
It can still be extracted: https://github.com/keith/dyld-shared-cache-extractor

I do not have any Apple system, so I cannot test.

**Comment by seidnerj** [comment]
Great, much appreciated!
